import type { Diagram, Table, Column, RelationEdge } from '@/types';

export function generateSQL(diagram: Diagram): string {
  const lines: string[] = [];
  const tables = diagram.nodes.map((n) => n.data.table);

  lines.push(`-- ============================================`);
  lines.push(`-- Generated by astoDB · Visual SQL Server Modeler`);
  lines.push(`-- Diagram: ${diagram.name}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Target: Microsoft SQL Server (T-SQL)`);
  lines.push(`-- ============================================`);
  lines.push('');
  lines.push('SET QUOTED_IDENTIFIER ON;');
  lines.push('SET ANSI_NULLS ON;');
  lines.push('GO');
  lines.push('');

  for (const table of tables) {
    lines.push(buildCreateTable(table));
    lines.push('GO');
    lines.push('');
  }

  const fkStatements = buildForeignKeys(diagram.edges, tables);
  if (fkStatements.length > 0) {
    lines.push('-- --------------------------------------------');
    lines.push('-- Foreign Key Constraints');
    lines.push('-- --------------------------------------------');
    lines.push('');
    lines.push(...fkStatements);
  }

  return lines.join('\n');
}

function q(name: string): string {
  return `[${name}]`;
}

function tableRef(table: Table): string {
  return table.schema ? `${q(table.schema)}.${q(table.name)}` : q(table.name);
}

function buildCreateTable(table: Table): string {
  const lines: string[] = [];

  if (table.comment) lines.push(`-- ${table.comment}`);
  lines.push(`CREATE TABLE ${tableRef(table)} (`);

  const defs: string[] = table.columns.map((col) => `    ${buildColumnDef(col)}`);

  const pkCols = table.columns.filter((c) => c.isPrimaryKey);
  if (pkCols.length > 0) {
    defs.push(`    CONSTRAINT ${q(`pk_${table.name}`)} PRIMARY KEY (${pkCols.map((c) => q(c.name)).join(', ')})`);
  }

  table.columns.filter((c) => c.isUnique && !c.isPrimaryKey).forEach((c) => {
    defs.push(`    CONSTRAINT ${q(`uk_${table.name}_${c.name}`)} UNIQUE (${q(c.name)})`);
  });

  lines.push(defs.join(',\n'));
  lines.push(`);`);
  return lines.join('\n');
}

function buildColumnDef(col: Column): string {
  const parts: string[] = [q(col.name), col.type];
  if (col.isAutoIncrement) parts.push('IDENTITY(1,1)');
  parts.push(col.isNullable ? 'NULL' : 'NOT NULL');
  if (col.defaultValue !== undefined && col.defaultValue.trim() !== '') {
    parts.push(`DEFAULT ${formatDefaultValue(col.defaultValue, col.type)}`);
  }
  if (col.comment) parts.push(`/* ${col.comment} */`);
  return parts.join(' ');
}

// Niladic T-SQL builtins that are called without parentheses.
const NILADIC_FUNCTIONS = new Set(['CURRENT_TIMESTAMP', 'CURRENT_USER', 'SESSION_USER', 'SYSTEM_USER']);

function isFunctionDefault(value: string): boolean {
  const upper = value.toUpperCase();
  if (NILADIC_FUNCTIONS.has(upper)) return true;
  // A bare call like GETDATE() or NEWID() — case-insensitive, so "getdate()" isn't
  // mistaken for a text literal and quoted (which fails conversion on first use).
  return /^[A-Z_][A-Z0-9_]*\([^'"]*\)$/.test(upper);
}

type TypeFamily = 'bit' | 'numeric' | 'text' | 'other';

function typeFamily(type: string): TypeFamily {
  const upper = type.toUpperCase();
  if (upper.startsWith('BIT')) return 'bit';
  if (/^(INT|BIGINT|SMALLINT|TINYINT|DECIMAL|NUMERIC|FLOAT|REAL|MONEY|SMALLMONEY)/.test(upper)) return 'numeric';
  if (/^(N?VARCHAR|N?CHAR|N?TEXT)/.test(upper)) return 'text';
  return 'other';
}

/** Formats a column's default so it matches its declared type instead of just guessing from the
 *  literal's shape — e.g. 'true'/'false' on a BIT column, or a numeric-looking default meant as
 *  text (e.g. '007'), previously slipped through unquoted/mis-typed and only failed at runtime. */
function formatDefaultValue(rawValue: string, type: string): string {
  const value = rawValue.trim();
  if (isFunctionDefault(value)) return value;

  const family = typeFamily(type);
  const quoted = `'${value.replace(/'/g, "''")}'`;

  if (family === 'bit') {
    const lower = value.toLowerCase();
    if (lower === 'true') return '1';
    if (lower === 'false') return '0';
    if (value === '0' || value === '1') return value;
    return quoted;
  }
  if (family === 'text') return quoted;
  if (family === 'numeric') return /^-?\d+(\.\d+)?$/.test(value) ? value : quoted;
  // Dates and everything else: a numeric constant passes through as-is, anything else
  // (including date literals like '2024-01-01') needs quotes for SQL Server to parse it.
  return /^-?\d+(\.\d+)?$/.test(value) ? value : quoted;
}

function noRestrict(action: string | undefined, fallback: string): string {
  if (!action || action === 'RESTRICT') return fallback;
  return action;
}

function buildForeignKeys(edges: RelationEdge[], tables: Table[]): string[] {
  const statements: string[] = [];
  const tableMap = new Map(tables.map((t) => [t.id, t]));

  for (const edge of edges) {
    if (!edge.data) continue;
    const parentTable = tableMap.get(edge.source);
    const childTable = tableMap.get(edge.target);
    if (!parentTable || !childTable) continue;

    const parentCol = parentTable.columns.find((c) => c.id === edge.data!.sourceColumnId);
    const childCol = childTable.columns.find((c) => c.id === edge.data!.targetColumnId);
    if (!parentCol || !childCol) continue;

    const constraintName = edge.data.foreignKeyName || edge.data.label
      || `fk_${childTable.name}_${parentTable.name}_${childCol.name}`;

    // T-SQL does not have RESTRICT — NO ACTION is the equivalent.
    const onDelete = noRestrict(edge.data.onDelete, 'NO ACTION');
    const onUpdate = noRestrict(edge.data.onUpdate, 'NO ACTION');

    statements.push(
      `ALTER TABLE ${tableRef(childTable)}\n` +
      `    ADD CONSTRAINT ${q(constraintName)}\n` +
      `    FOREIGN KEY (${q(childCol.name)}) REFERENCES ${tableRef(parentTable)} (${q(parentCol.name)})\n` +
      `    ON DELETE ${onDelete} ON UPDATE ${onUpdate};`
    );
    statements.push('GO');
    statements.push('');

    // SQL Server, unlike MySQL/Postgres, does not index the FK column automatically —
    // without one, every DELETE/UPDATE on the parent table scans the child table.
    // Skip it when the column is already a PK or UNIQUE, since those already have an index.
    if (!childCol.isPrimaryKey && !childCol.isUnique) {
      statements.push(
        `CREATE INDEX ${q(`ix_${childTable.name}_${childCol.name}`)} ON ${tableRef(childTable)} (${q(childCol.name)});`
      );
      statements.push('GO');
      statements.push('');
    }
  }

  return statements;
}
